default_stages: [pre-commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/crate-ci/typos
    rev: v1.45.1
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: cargo-fmt-check
        name: cargo-fmt-check
        language: system
        entry: cargo fmt --all -- --check
        pass_filenames: false

      - id: cargo-check-workspace
        name: cargo-check-workspace
        language: system
        entry: cargo check --workspace
        pass_filenames: false
        stages: [pre-push]

      - id: cargo-check-wasm-lotus
        name: cargo-check-wasm-lotus
        language: system
        entry: cargo check -p lotus-explorer --target wasm32-unknown-unknown
        pass_filenames: false
        stages: [pre-push]
