# typos exceptions for this repository
# Prevent typos from flagging project-specific tokens and acronyms
[files]
extend-exclude = [
"apps/**/public/assets/",
"**/i18n/**",
]

[default.extend-words]
erro = "erro"
