name: Deploy to Codeberg Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  CARGO_PROFILE_RELEASE_LTO: "off"
  CARGO_PROFILE_RELEASE_CODEGEN_UNITS: "16"
  CARGO_PROFILE_RELEASE_DEBUG: "0"
  RUSTC_WRAPPER: "sccache"
  SCCACHE_GHA_ENABLED: "true"

jobs:
  build-apps:
    runs-on: codeberg-medium
    strategy:
      matrix:
        include:
          - app: index
            path: "/dioxus/"
          - app: lotus-explore-rs
            path: "/dioxus/lotus-explore-rs/"
          - app: json-count-rs
            path: "/dioxus/json-count-rs/"
          - app: mgf-precursor-erro-rs
            path: "/dioxus/mgf-precursor-erro-rs/"
          - app: smellfish-rs
            path: "/dioxus/smellfish-rs/"
          - app: lipid-selecto-rs
            path: "/dioxus/lipid-selecto-rs/"
    steps:
      - uses: https://github.com/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: https://github.com/Mozilla-Actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba
      - uses: https://github.com/Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6
        with:
          key: ${{ matrix.app }}
      - uses: https://github.com/cargo-bins/cargo-binstall@e00d2c94cc0067b77737821097a62d91c0301baa
      - name: Install dioxus-cli
        run: |
          cargo binstall dioxus-cli --version 0.7.10 --locked --no-confirm
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      - name: Fetch Ketcher Assets (lotus-explore-rs only)
        if: matrix.app == 'lotus-explore-rs'
        run: cargo run --release -p lotus-deploy --bin fetch-ketcher
        working-directory: apps/lotus-explore-rs
      - name: Build App
        working-directory: apps/${{ matrix.app }}
        run: dx build --release --platform web --debug-symbols false --base-path "${{ matrix.path }}"
      - name: Publish build output to Git staging
        uses: actions/git-pages@v2
        with:
          branch: build-stage-${{ matrix.app }}
          token: ${{ forge.token }}
          source: target/dx/${{ matrix.app }}/release/web/public
