[application]
name = "lipid-selecto-rs"
default_platform = "web"
asset_dir = "assets"

[web]
pre_compress = true

[web.app]
title = "Lipid Selecto-rs"

[web.watcher]
reload_html = true
watch_path = ["src", "assets"]
